version: '3.5'
services:     
  mysql:
    image: mysql:latest
    container_name: docker-compose-mysql
    restart: always
    volumes: 
      - mysql-data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=mandarinkb
    ports:
      - 3306:3306
    networks:
      - backend 
networks:
  backend:       
volumes:
  mysql-data:

# parth /var/lib/docker/volumes
