// Code generated by MockGen. DO NOT EDIT.
// Source: promotion_setting_domain.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/mandarinkb/go-unit-test-with-mockgen/model"
)

// MockPromotionSettingRepository is a mock of PromotionSettingRepository interface.
type MockPromotionSettingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPromotionSettingRepositoryMockRecorder
}

// MockPromotionSettingRepositoryMockRecorder is the mock recorder for MockPromotionSettingRepository.
type MockPromotionSettingRepositoryMockRecorder struct {
	mock *MockPromotionSettingRepository
}

// NewMockPromotionSettingRepository creates a new mock instance.
func NewMockPromotionSettingRepository(ctrl *gomock.Controller) *MockPromotionSettingRepository {
	mock := &MockPromotionSettingRepository{ctrl: ctrl}
	mock.recorder = &MockPromotionSettingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromotionSettingRepository) EXPECT() *MockPromotionSettingRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPromotionSettingRepository) Get(id int) (*model.PromotionSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.PromotionSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPromotionSettingRepositoryMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPromotionSettingRepository)(nil).Get), id)
}
