version: '3.5'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mandarinkb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
