CREATE TABLE USERS (
  USER_ID      NUMBER(20)    NOT NULL,
  USERNAME   VARCHAR(50) NOT NULL,
  PASSWORD   VARCHAR(250) NOT NULL,
  USER_ROLE   VARCHAR(50) NOT NULL
);
ALTER TABLE USERS
  ADD (
    CONSTRAINT USER_ID PRIMARY KEY (USER_ID)
);
CREATE SEQUENCE USER_ID START WITH 1;

