version: '3.5'
services:  
  upload-download:
    image: go-upload-download-file:latest
    container_name: upload-download-file
    volumes:
      - ./upload:/root/data-upload  # กรณีเขียน upload file 
    ports:
      - 8080:8080
    networks:
      - backend         
networks:
  backend:       

# parth /var/lib/docker/volumes
# comment press ctrl+/
