version: '3.5'
services:  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: docker-compose-elasticsearch
    restart: always
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 5209:9200 
  mariadb:
    image: mariadb:10.3
    container_name: docker-compose-mariadb
    restart: always
    volumes: 
      - mariadb-data:/var/lib/mysql
    environment: 
      # - MYSQL_ROOT_PASSWORD=mandarinkb
      - MYSQL_ROOT_PASSWORD=${MARIA_PASSWORD}
    ports:
      - 3306:3306 
  redis:
    image: redis:latest
    container_name: docker-compose-redis
    restart: always
    # command: redis-server --requirepass mandarinkb --appendonly yes
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - 6379:6379
  # go-api:
  #   image: go-api:latest
  #   container_name: docker-compose-go-start-bot
  #   depends_on:
  #     - mariadb
  #     - redis
  #     - elasticsearch
  #   ports:
  #     - 8080:8080
  #   # expose:
  #   #   - "8080"
networks: 
  default: 
    external: 
      name: project-final  
volumes:
  mariadb-data:
  elasticsearch-data:

# parth /var/lib/docker/volumes
